### ISSUE TITLE
Error after upgrading to 1.8.2

### ISSUE THREAD

**Issue by dangerusslee** [NicolasSiver/nodebb-plugin-ns-awards#16]
```
Apr 07 12:27:54 ip-172-30-3-69.ec2.internal nodebb[25913]: 2018-04-07T12:27:54.136Z [15335] - error:  TypeError: Cannot read property 'uid' of undefined
Apr 07 12:27:54 ip-172-30-3-69.ec2.internal nodebb[25913]: at /tank/nodebb/node_modules/nodebb-plugin-ns-awards/plugin/controller.js:326:54
Apr 07 12:27:54 ip-172-30-3-69.ec2.internal nodebb[25913]: at /tank/nodebb/node_modules/async/dist/async.js:1121:9
Apr 07 12:27:54 ip-172-30-3-69.ec2.internal nodebb[25913]: at eachOfArrayLike (/tank/nodebb/node_modules/async/dist/async.js:1055:9)
Apr 07 12:27:54 ip-172-30-3-69.ec2.internal nodebb[25913]: at eachOf (/tank/nodebb/node_modules/async/dist/async.js:1103:5)
Apr 07 12:27:54 ip-172-30-3-69.ec2.internal nodebb[25913]: at _asyncMap (/tank/nodebb/node_modules/async/dist/async.js:1119:5)
Apr 07 12:27:54 ip-172-30-3-69.ec2.internal nodebb[25913]: at Object.map (/tank/nodebb/node_modules/async/dist/async.js:1108:16)
Apr 07 12:27:54 ip-172-30-3-69.ec2.internal nodebb[25913]: at /tank/nodebb/node_modules/nodebb-plugin-ns-awards/plugin/controller.js:325:27
Apr 07 12:27:54 ip-172-30-3-69.ec2.internal nodebb[25913]: at nextTask (/tank/nodebb/node_modules/async/dist/async.js:5310:14)
Apr 07 12:27:54 ip-172-30-3-69.ec2.internal nodebb[25913]: at next (/tank/nodebb/node_modules/async/dist/async.js:5317:9)
Apr 07 12:27:54 ip-172-30-3-69.ec2.internal nodebb[25913]: at /tank/nodebb/node_modules/async/dist/async.js:958:16
Apr 07 12:27:54 ip-172-30-3-69.ec2.internal nodebb[25913]: at Settings.get (/tank/nodebb/node_modules/nodebb-plugin-ns-awards/plugin/settings.js:60:16)
Apr 07 12:27:54 ip-172-30-3-69.ec2.internal nodebb[25913]: at /tank/nodebb/node_modules/async/dist/async.js:66:19
Apr 07 12:27:54 ip-172-30-3-69.ec2.internal nodebb[25913]: at nextTask (/tank/nodebb/node_modules/async/dist/async.js:5310:14)
Apr 07 12:27:54 ip-172-30-3-69.ec2.internal nodebb[25913]: at Object.waterfall (/tank/nodebb/node_modules/async/dist/async.js:5320:5)
Apr 07 12:27:54 ip-172-30-3-69.ec2.internal nodebb[25913]: at Object.Controller.getPostsWithRewards (/tank/nodebb/node_modules/nodebb-plugin-ns-awards/plugin/controller.js:318:15)
Apr 07 12:27:54 ip-172-30-3-69.ec2.internal nodebb[25913]: at Object.Filter.getPosts [as method] (/tank/nodebb/node_modules/nodebb-plugin-ns-awards/plugin/filters.js:52:20)
Apr 07 12:27:54 ip-172-30-3-69.ec2.internal nodebb[25913]: 2018-04-07T12:27:54.137Z [15335] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
Apr 07 12:27:54 ip-172-30-3-69.ec2.internal nodebb[25913]: [cluster] Child Process (15329) has exited (code: 1, signal: null)
```

**Comment by NicolasSiver** [comment]
Hello,

When do you get this error? What page do you visit?

I have upgraded to `1.8.2` and admin panel is functioning and the topic view is working well.

![image](https://user-images.githubusercontent.com/135263/38467482-0e4630e0-3b07-11e8-9261-ef59915ad884.png)
