### ISSUE TITLE
Nodebb 1.11.1 crashes

### ISSUE THREAD

**Issue by fais3000** [NicolasSiver/nodebb-plugin-ns-awards#26]
```2019-01-08T04:48:11.746Z [4567/12190] - [31merror[39m: Cannot read property 'uid' of null
TypeError: Cannot read property 'uid' of null
    at /var/www/nodebb/node_modules/nodebb-plugin-ns-awards/plugin/controller.js:324:55
    at /var/www/nodebb/node_modules/async/dist/async.js:1135:9
    at eachOfArrayLike (/var/www/nodebb/node_modules/async/dist/async.js:1069:9)
    at eachOf (/var/www/nodebb/node_modules/async/dist/async.js:1117:5)
    at _asyncMap (/var/www/nodebb/node_modules/async/dist/async.js:1133:5)
    at Object.map (/var/www/nodebb/node_modules/async/dist/async.js:1122:16)
    at /var/www/nodebb/node_modules/nodebb-plugin-ns-awards/plugin/controller.js:323:27
    at nextTask (/var/www/nodebb/node_modules/async/dist/async.js:5324:14)
    at next (/var/www/nodebb/node_modules/async/dist/async.js:5331:9)
    at /var/www/nodebb/node_modules/async/dist/async.js:969:16
    at Settings.get (/var/www/nodebb/node_modules/nodebb-plugin-ns-awards/plugin/settings.js:60:16)
    at /var/www/nodebb/node_modules/async/dist/async.js:66:19
    at nextTask (/var/www/nodebb/node_modules/async/dist/async.js:5324:14)
    at Object.waterfall (/var/www/nodebb/node_modules/async/dist/async.js:5334:5)
    at Object.Controller.getPostsWithRewards (/var/www/nodebb/node_modules/nodebb-plugin-ns-awards/plugin/controller.js:316:15)
    at Object.Filter.getPosts [as method] (/var/www/nodebb/node_modules/nodebb-plugin-ns-awards/plugin/filters.js:52:20)
2019-01-08T04:48:11.747Z [4567/12190] - [32minfo[39m: [app] Shutdown (SIGTERM/SIGINT) Initialised.

Nodebb Version 1.11.1
Plugin version 5.1.0

**Comment by NicolasSiver** [comment]
Share more information. What you are doing. Where error is happening. For some reason returned `post` is not available (null)

**Comment by fais3000** [comment]
@NicolasSiver  Here is the setup on our website. In Profile.tpl we've following on personal (9.1.4) tpl
```
<!-- IMPORT partials/awards_profile_flex.tpl -->
<!-- IMPORT partials/account/custom_fields_flex.tpl -->
<!-- IMPORT partials/points_profile.tpl -->
```

While on post.tpl just `<!-- IMPORT partials/awards_topic.tpl -->` within current persona(9.1.4) tpl

This setup was working till Nodebb 1.10.2. After the update to 1.11.1, nodebb crashes randomly with the error at the top.

**Comment by NicolasSiver** [comment]
Do you use any other mods which could have an impact on post or post data?

**Comment by fais3000** [comment]
@NicolasSiver No, we have no other modification to post data.

Just to identify the problem, i've setup nodebb from scratch now. Here is how it is crashing

```
2019-01-14T06:02:53.332Z [4567/8266] - [33mwarn[39m: [widgets.render] passing a string is deprecated!, filter:widget.render:shoutbox. Please set hookData.html in your plugin.
2019-01-14T06:03:08.716Z [4567/8266] - [33mwarn[39m: [widgets.render] passing a string is deprecated!, filter:widget.render:shoutbox. Please set hookData.html in your plugin.
2019-01-14T06:04:09.555Z [4567/8266] - [31merror[39m: uncaughtException: Cannot read property 'uid' of null
TypeError: Cannot read property 'uid' of null
    at /var/www/community/node_modules/nodebb-plugin-ns-awards/plugin/controller.js:324:55
    at /var/www/community/node_modules/async/dist/async.js:1135:9
    at eachOfArrayLike (/var/www/community/node_modules/async/dist/async.js:1069:9)
    at eachOf (/var/www/community/node_modules/async/dist/async.js:1117:5)
    at _asyncMap (/var/www/community/node_modules/async/dist/async.js:1133:5)
    at Object.map (/var/www/community/node_modules/async/dist/async.js:1122:16)
    at /var/www/community/node_modules/nodebb-plugin-ns-awards/plugin/controller.js:323:27
    at nextTask (/var/www/community/node_modules/async/dist/async.js:5324:14)
    at next (/var/www/community/node_modules/async/dist/async.js:5331:9)
    at /var/www/community/node_modules/async/dist/async.js:969:16
    at Settings.get (/var/www/community/node_modules/nodebb-plugin-ns-awards/plugin/settings.js:60:16)
    at /var/www/community/node_modules/async/dist/async.js:66:19
    at nextTask (/var/www/community/node_modules/async/dist/async.js:5324:14)
    at Object.waterfall (/var/www/community/node_modules/async/dist/async.js:5334:5)
    at Object.Controller.getPostsWithRewards (/var/www/community/node_modules/nodebb-plugin-ns-awards/plugin/controller.js:316:15)
    at Object.Filter.getPosts [as method] (/var/www/community/node_modules/nodebb-plugin-ns-awards/plugin/filters.js:52:20) {"error":{},"stack":"TypeError: Cannot read property 'uid' of null\n    at /var/www/community/node_modules/nodebb-plugin-ns-awards/plugin/controller.js:324:55\n    at /var/www/community/node_modules/async/dist/async.js:1135:9\n    at eachOfArrayLike (/var/www/community/node_modules/async/dist/async.js:1069:9)\n    at eachOf (/var/www/community/node_modules/async/dist/async.js:1117:5)\n    at _asyncMap (/var/www/community/node_modules/async/dist/async.js:1133:5)\n    at Object.map (/var/www/community/node_modules/async/dist/async.js:1122:16)\n    at /var/www/community/node_modules/nodebb-plugin-ns-awards/plugin/controller.js:323:27\n    at nextTask (/var/www/community/node_modules/async/dist/async.js:5324:14)\n    at next (/var/www/community/node_modules/async/dist/async.js:5331:9)\n    at /var/www/community/node_modules/async/dist/async.js:969:16\n    at Settings.get (/var/www/community/node_modules/nodebb-plugin-ns-awards/plugin/settings.js:60:16)\n    at /var/www/community/node_modules/async/dist/async.js:66:19\n    at nextTask (/var/www/community/node_modules/async/dist/async.js:5324:14)\n    at Object.waterfall (/var/www/community/node_modules/async/dist/async.js:5334:5)\n    at Object.Controller.getPostsWithRewards (/var/www/community/node_modules/nodebb-plugin-ns-awards/plugin/controller.js:316:15)\n    at Object.Filter.getPosts [as method] (/var/www/community/node_modules/nodebb-plugin-ns-awards/plugin/filters.js:52:20)","exception":true,"date":"Mon Jan 14 2019 06:04:09 GMT+0000 (UTC)","process":{"pid":8266,"uid":0,"gid":0,"cwd":"/var/www/community","execPath":"/root/.nvm/versions/node/v8.9.3/bin/node","version":"v8.9.3","argv":["/root/.nvm/versions/node/v8.9.3/bin/node","/var/www/community/app.js"],"memoryUsage":{"rss":305364992,"heapTotal":237092864,"heapUsed":193192584,"external":50891157}},"os":{"loadavg":[3.87744140625,4.37353515625,4.3330078125],"uptime":4002870},"trace":[{"column":55,"file":"/var/www/community/node_modules/nodebb-plugin-ns-awards/plugin/controller.js","function":null,"line":324,"method":null,"native":false},{"column":9,"file":"/var/www/community/node_modules/async/dist/async.js","function":null,"line":1135,"method":null,"native":false},{"column":9,"file":"/var/www/community/node_modules/async/dist/async.js","function":"eachOfArrayLike","line":1069,"method":null,"native":false},{"column":5,"file":"/var/www/community/node_modules/async/dist/async.js","function":"eachOf","line":1117,"method":null,"native":false},{"column":5,"file":"/var/www/community/node_modules/async/dist/async.js","function":"_asyncMap","line":1133,"method":null,"native":false},{"column":16,"file":"/var/www/community/node_modules/async/dist/async.js","function":"Object.map","line":1122,"method":"map","native":false},{"column":27,"file":"/var/www/community/node_modules/nodebb-plugin-ns-awards/plugin/controller.js","function":null,"line":323,"method":null,"native":false},{"column":14,"file":"/var/www/community/node_modules/async/dist/async.js","function":"nextTask","line":5324,"method":null,"native":false},{"column":9,"file":"/var/www/community/node_modules/async/dist/async.js","function":"next","line":5331,"method":null,"native":false},{"column":16,"file":"/var/www/community/node_modules/async/dist/async.js","function":null,"line":969,"method":null,"native":false},{"column":16,"file":"/var/www/community/node_modules/nodebb-plugin-ns-awards/plugin/settings.js","function":"Settings.get","line":60,"method":"get","native":false},{"column":19,"file":"/var/www/community/node_modules/async/dist/async.js","function":null,"line":66,"method":null,"native":false},{"column":14,"file":"/var/www/community/node_modules/async/dist/async.js","function":"nextTask","line":5324,"method":null,"native":false},{"column":5,"file":"/var/www/community/node_modules/async/dist/async.js","function":"Object.waterfall","line":5334,"method":"waterfall","native":false},{"column":15,"file":"/var/www/community/node_modules/nodebb-plugin-ns-awards/plugin/controller.js","function":"Object.Controller.getPostsWithRewards","line":316,"method":"getPostsWithRewards","native":false},{"column":20,"file":"/var/www/community/node_modules/nodebb-plugin-ns-awards/plugin/filters.js","function":"Object.Filter.getPosts [as method]","line":52,"method":"getPosts [as method]","native":false}]}
2019-01-14T06:04:09.558Z [4567/8266] - [31merror[39m: Cannot read property 'uid' of null
TypeError: Cannot read property 'uid' of null
    at /var/www/community/node_modules/nodebb-plugin-ns-awards/plugin/controller.js:324:55
    at /var/www/community/node_modules/async/dist/async.js:1135:9
    at eachOfArrayLike (/var/www/community/node_modules/async/dist/async.js:1069:9)
    at eachOf (/var/www/community/node_modules/async/dist/async.js:1117:5)
    at _asyncMap (/var/www/community/node_modules/async/dist/async.js:1133:5)
    at Object.map (/var/www/community/node_modules/async/dist/async.js:1122:16)
    at /var/www/community/node_modules/nodebb-plugin-ns-awards/plugin/controller.js:323:27
    at nextTask (/var/www/community/node_modules/async/dist/async.js:5324:14)
    at next (/var/www/community/node_modules/async/dist/async.js:5331:9)
    at /var/www/community/node_modules/async/dist/async.js:969:16
    at Settings.get (/var/www/community/node_modules/nodebb-plugin-ns-awards/plugin/settings.js:60:16)
    at /var/www/community/node_modules/async/dist/async.js:66:19
    at nextTask (/var/www/community/node_modules/async/dist/async.js:5324:14)
    at Object.waterfall (/var/www/community/node_modules/async/dist/async.js:5334:5)
    at Object.Controller.getPostsWithRewards (/var/www/community/node_modules/nodebb-plugin-ns-awards/plugin/controller.js:316:15)
    at Object.Filter.getPosts [as method] (/var/www/community/node_modules/nodebb-plugin-ns-awards/plugin/filters.js:52:20)
2019-01-14T06:04:09.559Z [4567/8266] - [32minfo[39m: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2019-01-14T06:04:09.566Z [4567/8266] - [32minfo[39m: [app] Web server closed to connections.
[cluster] Child Process (8266) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
```

**Comment by fais3000** [comment]
@NicolasSiver Ok, crashes are not random. This error occurs when user clicks "Chat" dropdown on the header.

**Comment by NicolasSiver** [comment]
Why would the plugin be used in the chats on your board?
Did you setup just with one plugin? Awards?

**Comment by fais3000** [comment]
@NicolasSiver We've not specifically added any changes in chat regarding awards. The exception gets thrown with chat event somehow though.

**Comment by yoyoyohamapi** [comment]
Same problem, post is null, then NodeBB crashed. @NicolasSiver :

```
TypeError: Cannot read property 'uid' of null
    at /var/www/nodebb/node_modules/nodebb-plugin-ns-awards/plugin/controller.js:324:55
```

So, may be code in [this line](https://github.com/NicolasSiver/nodebb-plugin-ns-awards/blob/231998f8fa044cc645a380e9608b3f3dac32435a/plugin/controller.js#L323) should filter  null posts:

```js
async.map(posts.filter(post => !!post), function (post, next) {
  // ...
}
```

**Comment by pig315** [comment]
the same +1

**Comment by NicolasSiver** [comment]
What exactly is the reason for the post to be `null`?
Do you have a post for deletion? Post from the guest?

**Comment by yoyoyohamapi** [comment]
> What exactly is the reason for the post to be `null`?
> Do you have a post for deletion? Post from the guest?

Yes, the post is deleted.
