### ISSUE TITLE
Callback is not a function on nodebb v1.13.0

### ISSUE THREAD

**Issue by digitalLumberjack** [NicolasSiver/nodebb-plugin-ns-awards#36]
Hi, when calling the plugin admin page on nodebb v1.13.0 the following error occurs:

```
nodebb_1                   | 2019-12-01T16:39:17.486Z [4567/151] - error: uncaughtException: callback is not a function
nodebb_1                   | TypeError: callback is not a function
nodebb_1                   |     at /opt/nodebb/node_modules/nodebb-plugin-ns-awards/plugin/sockets.js:91:13
nodebb_1                   |     at /opt/nodebb/node_modules/nodebb-plugin-ns-awards/node_modules/async/dist/async.js:473:16
nodebb_1                   |     at next (/opt/nodebb/node_modules/nodebb-plugin-ns-awards/node_modules/async/dist/async.js:5329:29)
nodebb_1                   |     at /opt/nodebb/node_modules/nodebb-plugin-ns-awards/node_modules/async/dist/async.js:969:16
nodebb_1                   |     at /opt/nodebb/node_modules/nodebb-plugin-ns-awards/node_modules/async/dist/async.js:1140:9
nodebb_1                   |     at /opt/nodebb/node_modules/nodebb-plugin-ns-awards/node_modules/async/dist/async.js:473:16
nodebb_1                   |     at iteratorCallback (/opt/nodebb/node_modules/nodebb-plugin-ns-awards/node_modules/async/dist/async.js:1064:13)
nodebb_1                   |     at /opt/nodebb/node_modules/nodebb-plugin-ns-awards/node_modules/async/dist/async.js:969:16
nodebb_1                   |     at /opt/nodebb/node_modules/nodebb-plugin-ns-awards/node_modules/async/dist/async.js:1137:13
nodebb_1                   |     at /opt/nodebb/node_modules/nodebb-plugin-ns-awards/plugin/controller.js:250:25 {"error":{},"stack":"TypeError: callback is not a function\n    at /opt/nodebb/node_modules/nodebb-plugin-ns-awards/plugin/sockets.js:91:13\n    at /opt/nodebb/node_modules/nodebb-plugin-ns-awards/node_modules/async/dist/async.js:473:16\n    at next (/opt/nodebb/node_modules/nodebb-plugin-ns-awards/node_modules/async/dist/async.js:5329:29)\n    at /opt/nodebb/node_modules/nodebb-plugin-ns-awards/node_modules/async/dist/async.js:969:16\n    at /opt/nodebb/node_modules/nodebb-plugin-ns-awards/node_modules/async/dist/async.js:1140:9\n    at /opt/nodebb/node_modules/nodebb-plugin-ns-awards/node_modules/async/dist/async.js:473:16\n    at iteratorCallback (/opt/nodebb/node_modules/nodebb-plugin-ns-awards/node_modules/async/dist/async.js:1064:13)\n    at /opt/nodebb/node_modules/nodebb-plugin-ns-awards/node_modules/async/dist/async.js:969:16\n    at /opt/nodebb/node_modules/nodebb-plugin-ns-awards/node_modules/async/dist/async.js:1137:13\n    at /opt/nodebb/node_modules/nodebb-plugin-ns-awards/plugin/controller.js:250:25","exception":true,"date":"Sun Dec 01 2019 16:39:17 GMT+0000 (UTC)","process":{"pid":151,"uid":0,"gid":0,"cwd":"/opt/nodebb","execPath":"/usr/local/bin/node","version":"v8.16.2","argv":["/usr/local/bin/node","/opt/nodebb/app.js"],"memoryUsage":{"rss":152141824,"heapTotal":122081280,"heapUsed":108288944,"external":36438704}},"os":{"loadavg":[0.08642578125,0.5107421875,0.47998046875],"uptime":28325},"trace":[{"column":13,"file":"/opt/nodebb/node_modules/nodebb-plugin-ns-awards/plugin/sockets.js","function":null,"line":91,"method":null,"native":false},{"column":16,"file":"/opt/nodebb/node_modules/nodebb-plugin-ns-awards/node_modules/async/dist/async.js","function":null,"line":473,"method":null,"native":false},{"column":29,"file":"/opt/nodebb/node_modules/nodebb-plugin-ns-awards/node_modules/async/dist/async.js","function":"next","line":5329,"method":null,"native":false},{"column":16,"file":"/opt/nodebb/node_modules/nodebb-plugin-ns-awards/node_modules/async/dist/async.js","function":null,"line":969,"method":null,"native":false},{"column":9,"file":"/opt/nodebb/node_modules/nodebb-plugin-ns-awards/node_modules/async/dist/async.js","function":null,"line":1140,"method":null,"native":false},{"column":16,"file":"/opt/nodebb/node_modules/nodebb-plugin-ns-awards/node_modules/async/dist/async.js","function":null,"line":473,"method":null,"native":false},{"column":13,"file":"/opt/nodebb/node_modules/nodebb-plugin-ns-awards/node_modules/async/dist/async.js","function":"iteratorCallback","line":1064,"method":null,"native":false},{"column":16,"file":"/opt/nodebb/node_modules/nodebb-plugin-ns-awards/node_modules/async/dist/async.js","function":null,"line":969,"method":null,"native":false},{"column":13,"file":"/opt/nodebb/node_modules/nodebb-plugin-ns-awards/node_modules/async/dist/async.js","function":null,"line":1137,"method":null,"native":false},{"column":25,"file":"/opt/nodebb/node_modules/nodebb-plugin-ns-awards/plugin/controller.js","function":null,"line":250,"method":null,"native":false}]}
nodebb_1                   | 2019-12-01T16:39:17.487Z [4567/151] - error: callback is not a function
nodebb_1                   | 2019-12-01T16:39:17.488Z [4567/151] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
```

**Comment by MikaXII** [comment]
I think it was the same issue :
https://community.nodebb.org/topic/14367/problem-with-socket-in-plugin-after-1-12-2-1-13-0-upgrade/2?_=1575377807732&lang=fr
