### ISSUE TITLE
nodebb 0.9.2 - crash report

### ISSUE THREAD

**Issue by sohrabafard** [NicolasSiver/nodebb-plugin-ns-awards#5]
```
error: TypeError: Cannot read property 'uid' of undefined
at /.../nodebb-plugin-ns-awards/plugin/controller.js:186:54
at /.../node_modules/async/lib/async.js:356:13
at async.forEachOf.async.eachOf (/home/nodeBB/forum/node_modules/async/lib/async.js:233:13)
at _asyncMap (/.../node_modules/async/lib/async.js:355:9)
at Object.map (..../node_modules/async/lib/async.js:337:20)
at /.../node_modules/nodebb-plugin-ns-awards/plugin/controller.js:184:27
at fn (/..../node_modules/async/lib/async.js:741:34)
at /..../node_modules/async/lib/async.js:1208:16
at ..../node_modules/async/lib/async.js:166:37
at /..../node_modules/async/lib/async.js:701:43
```

**Comment by NicolasSiver** [comment]
@sohrabafard  Provide also information what actions you have done.

**Comment by sohrabafard** [comment]
Noting, just see forum topics and posts and ACP!

**Comment by NicolasSiver** [comment]
I have upgraded to `0.9.3` just by visiting topics, everything is good. If you still experience same problem, try to provide more information, maybe there is conflict with another plugins, etc.
