### ISSUE TITLE
error opening /user/:userslug page on v2.8.1

### ISSUE THREAD

**Issue by Frozen-byte** [NicolasSiver/nodebb-plugin-ns-awards#61]
on v2.8.1, when opening my own user profile:
<img width="823" alt="image" src="https://user-images.githubusercontent.com/3965439/212392673-020a2447-762e-41f3-86a7-b45f353e87d6.png">

```
2023-01-13T18:25:30.091Z [4567/89082] - error: GET /user/admin
TypeError: Cannot read properties of undefined (reading 'uid')
    at /home/frozen_byte/Projects/nodebb-plugin-ns-awards/plugin/controller.js:193:54
    at nextTask (/home/frozen_byte/Projects/nodebb-plugin-ns-awards/node_modules/async/dist/async.js:5759:13)
    at next (/home/frozen_byte/Projects/nodebb-plugin-ns-awards/node_modules/async/dist/async.js:5767:13)
    at /home/frozen_byte/Projects/nodebb-plugin-ns-awards/node_modules/async/dist/async.js:327:20
    at Settings.get (/home/frozen_byte/Projects/nodebb-plugin-ns-awards/plugin/settings.js:60:16)
    at /home/frozen_byte/Projects/nodebb-plugin-ns-awards/node_modules/async/dist/async.js:53:33
    at nextTask (/home/frozen_byte/Projects/nodebb-plugin-ns-awards/node_modules/async/dist/async.js:5759:13)
    at Object.waterfall (/home/frozen_byte/Projects/nodebb-plugin-ns-awards/node_modules/async/dist/async.js:5770:9)
    at Object.awaitable (/home/frozen_byte/Projects/nodebb-plugin-ns-awards/node_modules/async/dist/async.js:211:32)
    at Object.Controller.getAccountWithRewards (/home/frozen_byte/Projects/nodebb-plugin-ns-awards/plugin/controller.js:186:15)
```

**Comment by Frozen-byte** [comment]
I think the issue is on `plugin/filter.js:16` since the `payload` argument does not contain `userData` but `templateData`.

**Comment by Frozen-byte** [comment]
solved with: https://github.com/NicolasSiver/nodebb-plugin-ns-awards/pull/59

just wanted to create my own PR as I saw this, lol.
